version: "3.3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: superhero
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      # - ./app/node_modules
    environment:
      - CHOKDIR_USERPOOLING=true
